// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace MappingEdu.Core.DataAccess.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Base : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Base));
        
        string IMigrationMetadata.Id
        {
            get { return "201412290501097_Base"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
