// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace MappingEdu.Core.DataAccess.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class IncreaseSizeOfSystemVersion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncreaseSizeOfSystemVersion));
        
        string IMigrationMetadata.Id
        {
            get { return "201503122252461_IncreaseSizeOfSystemVersion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
