// <auto-generated />
namespace MappingEdu.Core.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IX_SystemItemMap_MappingProjectId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IX_SystemItemMap_MappingProjectId));
        
        string IMigrationMetadata.Id
        {
            get { return "202003181400295_IX_SystemItemMap_MappingProjectId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
